# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adcf2de471ff325078d4e2a44b01e882edd754a57d170636f4dcefa6524b948b4207252cc9c2fbad532631492f8f53422f7f5a2ad9cc50a03d596ae44f3ad9e0

test:
  secret_key_base: 754a67dfc83399572e657dda347344c52e1c179ef555f680f9564fd683036136fca697090df8bf6be55b427e7b5b205ac850eacf328e8ad56961059b13590cb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
